run-dev:
	air -c .air.toml
migrate-up:
	migrate -source migrations -database postgres://user:password@localhost/database up
migrate-up:
	migrate -source migrations -database postgres://user:password@localhost/database down